#!/usr/bin/env bash

set -ex

sha=$(git rev-parse HEAD)
self_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)

# docker pull ghcr.io/griwes/reaveros-build-env/unpruned:latest
docker run -t -v $(pwd):/reaveros --name reaveros-docker-update-${sha}-full ghcr.io/griwes/reaveros-build-env/unpruned:latest /usr/bin/env bash -c '
    set -xe
    set -o pipefail

    apt update
    apt install build-essential automake cmake git python3 bison flex libssl-dev ccache cpio -y
    apt full-upgrade -y
    apt clean

    cd /build
    cmake . -DREAVEROS_ENABLE_UNIT_TESTS=ON
    make all-toolchain -j$(nproc) | tee /reaveros/docker/.build-log
' || { rm -f docker/.build-log; docker rm reaveros-docker-update-${sha}-full; "${self_dir}"/build-image; exit; }

# If only lines like "[xxx%] Built target ..." were printed, everything was up to date.
if [ -f docker/.build-log ] && ! cat docker/.build-log | grep -v Built -q
then
    docker tag ghcr.io/griwes/reaveros-build-env/unpruned:latest ghcr.io/griwes/reaveros-build-env/unpruned:${sha}

    docker pull ghcr.io/griwes/reaveros-build-env:latest
    docker tag ghcr.io/griwes/reaveros-build-env:latest ghcr.io/griwes/reaveros-build-env:${sha}

    rm docker/.build-log

    exit 0
fi

rm docker/.build-log

docker export reaveros-docker-update-${sha}-full \
    | docker import - --change "CMD /usr/bin/env bash" ghcr.io/griwes/reaveros-build-env/unpruned:${sha}

docker tag ghcr.io/griwes/reaveros-build-env/unpruned:${sha} ghcr.io/griwes/reaveros-build-env/unpruned:latest

docker run -v $(pwd):/reaveros --name reaveros-docker-update-${sha} ghcr.io/griwes/reaveros-build-env/unpruned:latest /usr/bin/env bash -c '
    set -xe

    cd /build
    make all-toolchain-prune -j$(nproc)
'

docker export reaveros-docker-update-${sha} \
    | docker import - --change "CMD /usr/bin/env bash" ghcr.io/griwes/reaveros-build-env:${sha}

docker tag ghcr.io/griwes/reaveros-build-env:${sha} ghcr.io/griwes/reaveros-build-env:latest

