name: Daily maintenance

on:
    push:
        branch:
          - automatic-toolchain-upgrades
    schedule:
          - cron: '0 4 * * *'

jobs:
    update:
        name: Update build-env containers
        runs-on: ubuntu-latest

        steps:
          - name: Check out the repository
            uses: actions/checkout@v2

          - name: Update containers
            run: ./docker/update-images

          - name: Login to ghcr.io
            run: |
                docker login https://ghcr.io -u '${{ github.actor }}' -p '${{ secrets.GITHUB_TOKEN }}'

          - name: Push containers
            run: |
                docker push ghcr.io/griwes/reaveros-build-env/unpruned:${{ github.sha }}
                docker push ghcr.io/griwes/reaveros-build-env:${{ github.sha }}

          - name: Push the latest tag
            if: ${{ github.event_name == 'schedule' }}
            run: |
                docker push ghcr.io/griwes/reaveros-build-env/unpruned:latest
                docker push ghcr.io/griwes/reaveros-build-env:latest

    versions:
        name: Trigger toolchain version updates
        runs-on: ubuntu-latest

        steps:
          - name: Check out the repository
            uses: actions/checkout@v2

          - name: Setup git
            run: |
                git config user.name "Reaver Project CI"
                git config user.email "ci@reaver-project.org"

          - name: Run toolchain update
            env:
                GITHUB_TOKEN: ${{ secrets.CI_TOKEN }}
            run: ./maintenance/update-toolchains --pr
